### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by Kongaloosh** [csarven/ldn-tests#17]
<img width="592" alt="screen shot 2017-03-01 at 10 18 12 am" src="https://cloud.githubusercontent.com/assets/1590729/23471947/698648aa-fe68-11e6-8cb5-02529f235207.png">

I'm getting a proxy error when I try to run the test suit against the receiver I'm working on.

URL:
`http://kongaloosh.com/inbox`

Data:
`{
  "@context": "https://www.w3.org/ns/activitystreams",
  "@id": "",
  "@type": "Announce",
  "actor": "https://rhiaro.co.uk/#me",
  "object": "http://example.net/note",
  "target": "http://example.org/article",
  "updated": "2016-06-28T19:56:20.114Z"
}`

Checking my logs, I get to the point where it's fetching and returning JSON, it returns a response and after that no further requests are received.

**Comment by csarven** [comment]
Good catch. Thank you for the issue.

The `POST` request appears to work fine (it returns `HTTP 202` in your case).

The issue appears to originate from the test not handling the response to the `GET` request with an empty body. Technically an empty content is not valid JSON-LD (your receiver is returning `Content-Type: application/ld+json`) with the `HTTP 200` status code.

I updated the test code (since it was breaking in this case), and to also return a useful message for the test: "Returns JSON-LD on GET requests."

Let me know if the following is clear:

>`HTTP 200` received but it had an empty body (invalid JSON-LD). Consider returning `HTTP 200` with `{ "@id": "", "http://www.w3.org/ns/ldp#contains": [] }`, or an `HTTP 4xx` if that was the real intention, and check the checkbox for "Receiver should reject this notification" in the test form.

You can re-test.

**Comment by Kongaloosh** [comment]
That makes a lot of sense. Thanks for following up!

**Comment by csarven** [comment]
@Kongaloosh Are we okay to close this issue? Did it work out for your implementation? How about the tests and report?

**Comment by Kongaloosh** [comment]
yeah, had a chance to fix things and make sure it's working.
