### ISSUE TITLE
Check notification is retreivable as JSON-LD

### ISSUE THREAD

**Issue by rhiaro** [csarven/ldn-tests#3]
Doing a GET on the notification with an Accept Header of `application/ld+json` or `*/*` should return a valid JSON-LD body.

Not sure about a GET with no Accept header. Maybe issue a warning if JSON-LD is not returned?

**Comment by csarven** [comment]
If no Accept given, the assumption is that the server return the response in an RDF format of their preference. I think the best thing to do would be to see if the response body is valid as per the Content-Type that it is returned with (which gets a PASS), and FAIL otherwise.

**Comment by csarven** [comment]
Tests each notification in Inbox with request `Accept` header `application/ld+json` and `*/*`, as well as without `Accept`. If the resource can't be retrieved, or if there is a single failure in reserialization, or if the request uses `application/ld+json` but returned with something else, then the whole section is marked as a fail. Otherwise, pass.
